apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: multicloud-platform
  namespace: argocd
spec:
  description: Central services for the multi-cloud platform

  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - git@gitlab.com:skcloud2007/multicloud-platform-bootstrap.git
    - git@gitlab.com:skcloud2007/multicloud-helm-charts.git

  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: monitoring-agent
      name: eks-dev
    - namespace: monitoring-agent
      name: eks-prod
    - namespace: monitoring-agent
      name: aks-dev
    - namespace: monitoring-agent
      name: aks-prod
    - namespace: monitoring-agent
      name: gke-dev
    - namespace: monitoring-agent
      name: gke-prod

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: Secret
        name: central-monitoring-admission
      - group: ""
        kind: Secret
        name: central-monitoring-grafana-admin
      - kind: Secret
        name: central-monitoring-slack-webhook
