apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "multicloud-monitoring-agent.fullname" . }}
  labels:
    {{- include "multicloud-monitoring-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - services
      - endpoints
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "multicloud-monitoring-agent.fullname" . }}
  labels:
    {{- include "multicloud-monitoring-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "multicloud-monitoring-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "multicloud-monitoring-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
