apiVersion: v1
kind: Service
metadata:
  name: {{ include "multicloud-monitoring-agent.fullname" . }}
  labels:
    {{- include "multicloud-monitoring-agent.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "multicloud-monitoring-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 9090
      targetPort: http
